### ISSUE TITLE
Disclaimer alert

### ISSUE THREAD

**Issue by kauffmanes** [kauffmanes/infsci-2620-final#8]
We should add a legal disclaimer when you sign up or read/post on a question that the answers are not supposed to be taken as actual medical advice and that we take no responsibility for dumb answers.

**Comment by Lazarus1993** [comment]
Yeah that makes sense. I will be able to work on it tonight.

**Comment by Lazarus1993** [comment]
I have added the Terms and Conditions and HIPAA rules
